# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 20, 421, 111))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("logo (1).png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 0, 800, 600))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../../Downloads/WhiteGrey.png"))
        self.label_3.setIndent(0)
        self.label_3.setObjectName("label_3")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(190, 150, 414, 314))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setStyleSheet("font: 75 20pt \"Arial\";")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.pushButton_6 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_6.setMinimumSize(QtCore.QSize(121, 31))
        self.pushButton_6.setStyleSheet("\n"
"QPushButton{\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid rgb(171, 171, 171);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(255, 226, 229);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(218, 30, 60);\n"
"    color: rgb(255, 255, 255)\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout.addWidget(self.pushButton_6)
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_5.setMinimumSize(QtCore.QSize(121, 31))
        self.pushButton_5.setStyleSheet("\n"
"QPushButton{\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid rgb(171, 171, 171);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(255, 226, 229);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(218, 30, 60);\n"
"    color: rgb(255, 255, 255)\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_4.setMinimumSize(QtCore.QSize(121, 31))
        self.pushButton_4.setStyleSheet("\n"
"QPushButton{\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid rgb(171, 171, 171);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(255, 226, 229);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(218, 30, 60);\n"
"    color: rgb(255, 255, 255)\n"
"}\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setMinimumSize(QtCore.QSize(121, 31))
        self.pushButton.setStyleSheet("\n"
"QPushButton{\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid rgb(171, 171, 171);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(255, 226, 229);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(218, 30, 60);\n"
"    color: rgb(255, 255, 255)\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(121, 31))
        self.pushButton_3.setStyleSheet("\n"
"QPushButton{\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid rgb(171, 171, 171);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(255, 226, 229);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(218, 30, 60);\n"
"    color: rgb(255, 255, 255)\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(121, 31))
        self.pushButton_2.setStyleSheet("\n"
"QPushButton{\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid rgb(171, 171, 171);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(255, 226, 229);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(218, 30, 60);\n"
"    color: rgb(255, 255, 255)\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.layoutWidget.raise_()
        self.label_3.raise_()
        self.label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600; color:#354447;\">Admin Preference Menu</span></p></body></html>"))
        self.pushButton_6.setText(_translate("MainWindow", "Admin Menu"))
        self.pushButton_5.setText(_translate("MainWindow", "Mentor Interview"))
        self.pushButton_4.setText(_translate("MainWindow", "Interviews"))
        self.pushButton.setText(_translate("MainWindow", "Applications"))
        self.pushButton_3.setText(_translate("MainWindow", "Main Menu"))
        self.pushButton_2.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
