# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adminmenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 600)
        Dialog.setMaximumSize(QtCore.QSize(800, 600))
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(330, 180, 401, 361))
        self.tableWidget.setStyleSheet("QTableWidget {\n"
"    background-color: #2a2d33;\n"
"    color: white;\n"
"    gridline-color: #444;\n"
"    selection-background-color: #50555e;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #3c414a;\n"
"    color: white;\n"
"    padding: 4px;\n"
"    border: 1px solid #444;\n"
"}")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.frame_header = QtWidgets.QFrame(Dialog)
        self.frame_header.setGeometry(QtCore.QRect(30, 180, 281, 331))
        font = QtGui.QFont()
        font.setFamily("Academy Engraved LET")
        font.setPointSize(12)
        self.frame_header.setFont(font)
        self.frame_header.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_header.setObjectName("frame_header")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_header)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_content = QtWidgets.QFrame(self.frame_header)
        self.frame_content.setMaximumSize(QtCore.QSize(320, 16777215))
        self.frame_content.setObjectName("frame_content")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.frame_content)
        self.vboxlayout.setSpacing(12)
        self.vboxlayout.setObjectName("vboxlayout")
        self.label_2 = QtWidgets.QLabel(self.frame_content)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("font: 75 20pt \"Arial\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.vboxlayout.addWidget(self.label_2)
        self.backgroung_png = QtWidgets.QLabel(self.frame_content)
        self.backgroung_png.setText("")
        self.backgroung_png.setPixmap(QtGui.QPixmap("../../Downloads/WhiteGrey.png"))
        self.backgroung_png.setObjectName("backgroung_png")
        self.vboxlayout.addWidget(self.backgroung_png)
        self.pushButton_mail = QtWidgets.QPushButton(self.frame_content)
        self.pushButton_mail.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid rgb(171, 171, 171);\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"min-height: 40px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 226, 229);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(218, 30, 60);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_mail.setObjectName("pushButton_mail")
        self.vboxlayout.addWidget(self.pushButton_mail)
        self.pushButton_event = QtWidgets.QPushButton(self.frame_content)
        self.pushButton_event.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid rgb(171, 171, 171);\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"min-height: 40px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 226, 229);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(218, 30, 60);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_event.setObjectName("pushButton_event")
        self.vboxlayout.addWidget(self.pushButton_event)
        self.pushButton_settings = QtWidgets.QPushButton(self.frame_content)
        self.pushButton_settings.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid rgb(171, 171, 171);\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"min-height: 40px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 226, 229);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(218, 30, 60);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_settings.setObjectName("pushButton_settings")
        self.vboxlayout.addWidget(self.pushButton_settings)
        self.pushButton_exit = QtWidgets.QPushButton(self.frame_content)
        self.pushButton_exit.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid rgb(171, 171, 171);\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"min-height: 40px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 226, 229);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(218, 30, 60);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.vboxlayout.addWidget(self.pushButton_exit)
        self.verticalLayout_3.addWidget(self.frame_content)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(220, 10, 341, 121))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("logo (1).png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Event Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Start Time"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Participant Mail"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Organizer Email"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600; color:#354449;\">ADMIN MENU</span></p></body></html>"))
        self.pushButton_mail.setText(_translate("Dialog", "SEND MAIL"))
        self.pushButton_event.setText(_translate("Dialog", "EVENT CONTROL"))
        self.pushButton_settings.setText(_translate("Dialog", "PREFERENCES - ADMIN"))
        self.pushButton_exit.setText(_translate("Dialog", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
