# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'application.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 10, 491, 61))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.exit_button = QtWidgets.QPushButton(self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(10, 720, 241, 41))
        self.exit_button.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid rgb(171, 171, 171);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(255, 226, 229);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(218, 30, 60);\n"
"    color: rgb(255, 255, 255)\n"
"}")
        self.exit_button.setObjectName("exit_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 231, 61))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("logo (1).png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.app_list = QtWidgets.QTableWidget(self.centralwidget)
        self.app_list.setGeometry(QtCore.QRect(270, 80, 501, 471))
        self.app_list.setObjectName("app_list")
        self.app_list.setColumnCount(8)
        self.app_list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.app_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.app_list.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.app_list.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.app_list.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.app_list.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.app_list.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.app_list.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.app_list.setHorizontalHeaderItem(7, item)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 80, 251, 471))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.search_line_edit = QtWidgets.QLineEdit(self.widget)
        self.search_line_edit.setText("")
        self.search_line_edit.setClearButtonEnabled(True)
        self.search_line_edit.setObjectName("search_line_edit")
        self.verticalLayout.addWidget(self.search_line_edit)
        self.search_button = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.search_button.setFont(font)
        self.search_button.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid rgb(171, 171, 171);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(255, 226, 229);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(218, 30, 60);\n"
"    color: rgb(255, 255, 255)\n"
"}")
        self.search_button.setObjectName("search_button")
        self.verticalLayout.addWidget(self.search_button)
        self.all_app_button = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.all_app_button.setFont(font)
        self.all_app_button.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid rgb(171, 171, 171);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(255, 226, 229);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(218, 30, 60);\n"
"    color: rgb(255, 255, 255)\n"
"}")
        self.all_app_button.setObjectName("all_app_button")
        self.verticalLayout.addWidget(self.all_app_button)
        self.planned_button = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.planned_button.setFont(font)
        self.planned_button.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid rgb(171, 171, 171);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(255, 226, 229);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(218, 30, 60);\n"
"    color: rgb(255, 255, 255)\n"
"}")
        self.planned_button.setObjectName("planned_button")
        self.verticalLayout.addWidget(self.planned_button)
        self.unplanned_button = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.unplanned_button.setFont(font)
        self.unplanned_button.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid rgb(171, 171, 171);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(255, 226, 229);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(218, 30, 60);\n"
"    color: rgb(255, 255, 255)\n"
"}")
        self.unplanned_button.setObjectName("unplanned_button")
        self.verticalLayout.addWidget(self.unplanned_button)
        self.mentor_meeting_button = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.mentor_meeting_button.setFont(font)
        self.mentor_meeting_button.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid rgb(171, 171, 171);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(255, 226, 229);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(218, 30, 60);\n"
"    color: rgb(255, 255, 255)\n"
"}")
        self.mentor_meeting_button.setObjectName("mentor_meeting_button")
        self.verticalLayout.addWidget(self.mentor_meeting_button)
        self.previous_button = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.previous_button.setFont(font)
        self.previous_button.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid rgb(171, 171, 171);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(255, 226, 229);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(218, 30, 60);\n"
"    color: rgb(255, 255, 255)\n"
"}")
        self.previous_button.setObjectName("previous_button")
        self.verticalLayout.addWidget(self.previous_button)
        self.repeated_button = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.repeated_button.setFont(font)
        self.repeated_button.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid rgb(171, 171, 171);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(255, 226, 229);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(218, 30, 60);\n"
"    color: rgb(255, 255, 255)\n"
"}")
        self.repeated_button.setObjectName("repeated_button")
        self.verticalLayout.addWidget(self.repeated_button)
        self.different_button = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.different_button.setFont(font)
        self.different_button.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid rgb(171, 171, 171);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(255, 226, 229);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(218, 30, 60);\n"
"    color: rgb(255, 255, 255)\n"
"}")
        self.different_button.setObjectName("different_button")
        self.verticalLayout.addWidget(self.different_button)
        self.filter_app_button = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.filter_app_button.setFont(font)
        self.filter_app_button.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid rgb(171, 171, 171);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(255, 226, 229);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(218, 30, 60);\n"
"    color: rgb(255, 255, 255)\n"
"}")
        self.filter_app_button.setObjectName("filter_app_button")
        self.verticalLayout.addWidget(self.filter_app_button)
        self.back_button = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.back_button.setFont(font)
        self.back_button.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid rgb(171, 171, 171);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(255, 226, 229);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(218, 30, 60);\n"
"    color: rgb(255, 255, 255)\n"
"}")
        self.back_button.setObjectName("back_button")
        self.verticalLayout.addWidget(self.back_button)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600; color:#334548;\">PROJECT APPLICATIONS</span></p></body></html>"))
        self.exit_button.setText(_translate("MainWindow", "Exit"))
        item = self.app_list.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Date"))
        item = self.app_list.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name Surname"))
        item = self.app_list.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Mail"))
        item = self.app_list.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Telephone"))
        item = self.app_list.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Post Code"))
        item = self.app_list.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "State"))
        item = self.app_list.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Status"))
        item = self.app_list.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Economical \n"
"Situation"))
        self.search_line_edit.setPlaceholderText(_translate("MainWindow", "Search any word..."))
        self.search_button.setText(_translate("MainWindow", "Search"))
        self.all_app_button.setText(_translate("MainWindow", "All Applications"))
        self.planned_button.setText(_translate("MainWindow", "Planned Mentor Meeting"))
        self.unplanned_button.setText(_translate("MainWindow", "Unscheduled Mentor Meeting"))
        self.mentor_meeting_button.setText(_translate("MainWindow", "Mentor Meeting"))
        self.previous_button.setText(_translate("MainWindow", "Previous VIT Control"))
        self.repeated_button.setText(_translate("MainWindow", "Repeated Registration"))
        self.different_button.setText(_translate("MainWindow", "Different Registration"))
        self.filter_app_button.setText(_translate("MainWindow", "Filter Application"))
        self.back_button.setText(_translate("MainWindow", "Back to the Menu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
