# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.icon = QtWidgets.QLabel(self.centralwidget)
        self.icon.setGeometry(QtCore.QRect(130, 50, 471, 131))
        self.icon.setText("")
        self.icon.setPixmap(QtGui.QPixmap("logo (1).png"))
        self.icon.setScaledContents(True)
        self.icon.setObjectName("icon")

        self.user_name_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.user_name_lineedit.setGeometry(QtCore.QRect(280, 220, 261, 41))
        self.user_name_lineedit.setObjectName("user_name_lineedit")

        self.user_name_label = QtWidgets.QLabel(self.centralwidget)
        self.user_name_label.setGeometry(QtCore.QRect(180, 220, 91, 41))
        self.user_name_label.setObjectName("user_name_label")

        self.password_label = QtWidgets.QLabel(self.centralwidget)
        self.password_label.setGeometry(QtCore.QRect(180, 280, 91, 41))
        self.password_label.setObjectName("password_label")

        self.password_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.password_lineedit.setGeometry(QtCore.QRect(280, 280, 261, 41))
        self.password_lineedit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_lineedit.setObjectName("password_lineedit")

        self.show_password = QtWidgets.QCheckBox(self.centralwidget)
        self.show_password.setGeometry(QtCore.QRect(550, 290, 75, 20))
        self.show_password.setObjectName("show_password")

        self.login_button = QtWidgets.QPushButton(self.centralwidget)
        self.login_button.setGeometry(QtCore.QRect(280, 350, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.login_button.setFont(font)
        self.login_button.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid rgb(171, 171, 171);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(255, 226, 229);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(218, 30, 60);\n"
"    color: rgb(255, 255, 255)\n"
"}")
        self.login_button.setObjectName("login_button")

        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(440, 350, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.exit.setFont(font)
        self.exit.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid rgb(171, 171, 171);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(255, 226, 229);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(218, 30, 60);\n"
"    color: rgb(255, 255, 255)\n"
"}")
        self.exit.setObjectName("exit")

        self.backgroung_png = QtWidgets.QLabel(self.centralwidget)
        self.backgroung_png.setGeometry(QtCore.QRect(-20, -25, 800, 600))
        self.backgroung_png.setMaximumSize(QtCore.QSize(800, 600))
        self.backgroung_png.setText("")
        self.backgroung_png.setPixmap(QtGui.QPixmap("../../Downloads/WhiteGrey.png"))
        self.backgroung_png.setObjectName("backgroung_png")

        # Layer ordering
        self.backgroung_png.raise_()
        self.icon.raise_()
        self.user_name_lineedit.raise_()
        self.user_name_label.raise_()
        self.password_label.raise_()
        self.password_lineedit.raise_()
        self.show_password.raise_()
        self.login_button.raise_()
        self.exit.raise_()

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        # Show/Hide password checkbox connection
        self.show_password.stateChanged.connect(self.toggle_password_visibility)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.user_name_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:700;\">Username :</span></p></body></html>"))
        self.password_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:700;\">Password :</span></p></body></html>"))
        self.show_password.setText(_translate("MainWindow", "Show"))
        self.login_button.setText(_translate("MainWindow", "Login"))
        self.exit.setText(_translate("MainWindow", "Exit"))

    # Password visibility toggle function
    def toggle_password_visibility(self, state):
        if state == QtCore.Qt.Checked:
            self.password_lineedit.setEchoMode(QtWidgets.QLineEdit.Normal)
        else:
            self.password_lineedit.setEchoMode(QtWidgets.QLineEdit.Password)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
