# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mentor_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(170, 150, 601, 291))
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tableWidget.setWordWrap(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignTop)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(340, 120, 437, 26))
        self.comboBox.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(70, 40, 261, 81))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("logo (1).png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(81, 1, 16, 16))
        self.label.setMaximumSize(QtCore.QSize(431, 111))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../logo_720.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(380, 60, 281, 41))
        self.label_2.setStyleSheet("font: 700 24pt \"Times New Roman\";\n"
"")
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 156, 143, 281))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setStyleSheet("QPushButton{\n"
"color:rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"border: 2px solid rgb(171, 171, 171);\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setStyleSheet("\n"
"QPushButton{\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid rgb(171, 171, 171);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(255, 226, 229);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(218, 30, 60);\n"
"    color: rgb(255, 255, 255)\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton_10 = QtWidgets.QPushButton(self.widget)
        self.pushButton_10.setMinimumSize(QtCore.QSize(141, 31))
        self.pushButton_10.setMaximumSize(QtCore.QSize(141, 31))
        self.pushButton_10.setStyleSheet("\n"
"QPushButton{\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid rgb(171, 171, 171);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(255, 226, 229);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(218, 30, 60);\n"
"    color: rgb(255, 255, 255)\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout.addWidget(self.pushButton_10)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setMinimumSize(QtCore.QSize(141, 31))
        self.pushButton_5.setMaximumSize(QtCore.QSize(141, 31))
        self.pushButton_5.setStyleSheet("\n"
"QPushButton{\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid rgb(171, 171, 171);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(255, 226, 229);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(218, 30, 60);\n"
"    color: rgb(255, 255, 255)\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.widget)
        self.pushButton_6.setMinimumSize(QtCore.QSize(141, 31))
        self.pushButton_6.setMaximumSize(QtCore.QSize(141, 31))
        self.pushButton_6.setStyleSheet("\n"
"QPushButton{\n"
"color:rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid rgb(171, 171, 171);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(255, 226, 229);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(218, 30, 60);\n"
"    color: rgb(255, 255, 255)\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout.addWidget(self.pushButton_6)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Meeting Date"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Full Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Mentor"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Sector Information"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Column 1 "))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Column 2 "))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Participant\'s Workload"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Column 3"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Participation in the full VIT Project is appropriate"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Referral to the first IT Training of the VIT Project is appropriate"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Referral to the English Training of the VIT Project is appropriate"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Referral within the VIT Project Framework is appropriate"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Direct Coaching and Job Placement is appropriate"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Participation in the next VIT Project would be more appropriate"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Should be referred to another sector"))
        self.comboBox.setItemText(7, _translate("MainWindow", "Other"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:36pt;\">MENTOR MENU</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Search"))
        self.pushButton_10.setText(_translate("MainWindow", "All Applications"))
        self.pushButton_5.setText(_translate("MainWindow", "Back Menu"))
        self.pushButton_6.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
